using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BaconsaleMovieCollection.Models
{
    public class MoviesContext : DbContext
    {
        //Constructor
        public MoviesContext(DbContextOptions<MoviesContext> options) : base(options)
        {
            //leave blank for now
        }
        public DbSet<ApplicationResponse> responses { get; set; }

        public DbSet<Category> categories { get; set; }

        //seeding the data
        protected override void OnModelCreating(ModelBuilder mb)
        {
            mb.Entity<Category>().HasData(
                new Category { CategoryID = 1, CategoryName = "Action/Adventure" },
                new Category { CategoryID = 2, CategoryName = "Comedy" },
                new Category { CategoryID = 3, CategoryName = "Drama" },
                new Category { CategoryID = 4, CategoryName = "Family" },
                new Category { CategoryID = 5, CategoryName = "Horror/Suspense" },
                new Category { CategoryID = 6, CategoryName = "Miscellaneous" },
                new Category { CategoryID = 7, CategoryName = "Television" },
                new Category { CategoryID = 8, CategoryName = "VHS" }
                );

            mb.Entity<ApplicationResponse>().HasData(
                new ApplicationResponse
                {
                    FirstName = "Michael",
                    LastName = "Scott",
                    International = "No",
                    Gender = "Male",
                    Email = "Michael.Scott@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2020,
                    Phone = "(888)867-5309",
                    BYUID = 665614397,
                    Position = "TA IS 201",
                    ClassCode = 26077,
                    EmpRecord = 0,
                    Supervisor = "David Wallace",
                    HireDate = "2020-01-03",
                    PayRate = 15.50,
                    LastPayIncrease = "2021-06-27",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-06-27",
                    YearInProgram = "MSB Core (IS or other)",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-01-03",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-04-01",
                    BYUName = "Scott, Michael",
                    
                },
                new ApplicationResponse
                {
                    FirstName = "Dwight",
                    LastName = "Schrute",
                    International = "No",
                    Gender = "Male",
                    Email = "Dwight.Schrute@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2022,
                    Phone = "(888)867-5310",
                    BYUID = 341054778,
                    Position = "RA",
                    ClassCode = 27432,
                    EmpRecord = 1,
                    Supervisor = "Michael Scott",
                    HireDate = "2020-01-04",
                    PayRate = 15.50,
                    LastPayIncrease = "2021-06-30",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-06-30",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-01-04",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-01-05",
                    BYUName = "Schrute, Dwight",
                },
                new ApplicationResponse
                {
                    FirstName = "Jim",
                    LastName = "Halpert",
                    International = "No",
                    Gender = "Male",
                    Email = "Jim.Halpert@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Spring",
                    Year = 2022,
                    Phone = "(888)867-5311",
                    BYUID = 339262687,
                    Position = "Office",
                    ClassCode = 23482,
                    EmpRecord = 2,
                    Supervisor = "Michael Scott",
                    HireDate = "2020-01-05",
                    PayRate = 15.50,
                    LastPayIncrease = "2021-06-30",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-06-30",
                    YearInProgram = "MBA",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-01-05",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-01-06",
                    BYUName = "Halpert, Jim",
                },

                new ApplicationResponse
                {
                    FirstName = "Pam",
                    LastName = "Beesly",
                    International = "Yes",
                    Gender = "Female",
                    Email = "Pam.Beesly@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Summer",
                    Year = 2020,
                    Phone = "(888)867-5312",
                    BYUID = 941986587,
                    Position = "Student Instructor",
                    ClassCode = 28332,
                    EmpRecord = 3,
                    Supervisor = "Michael Scott",
                    HireDate = "2020-01-06",
                    PayRate = 15.50,
                    LastPayIncrease = "2021-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-08-15",
                    YearInProgram = "MPA",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Checked",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-01-06",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-01-07",
                    BYUName = "Beesly, Pam",
                },

                new ApplicationResponse
                {
                    FirstName = "Ryan",
                    LastName = "Howard",
                    International = "No",
                    Gender = "Male",
                    Email = "Ryan.Howard@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2020,
                    Phone = "(888)867-5313",
                    BYUID = 495114604,
                    Position = "Other",
                    ClassCode = 21538,
                    EmpRecord = 0,
                    Supervisor = "Michael Scott",
                    HireDate = "2020-01-07",
                    PayRate = 15.50,
                    LastPayIncrease = "2021-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-08-15",
                    YearInProgram = "Macc",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Not Yet",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-01-07",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-01-08",
                    BYUName = "Howard, Ryan",
                },

                new ApplicationResponse
                {
                    FirstName = "Andy",
                    LastName = "Bernard",
                    International = "No",
                    Gender = "Male",
                    Email = "Andy.Bernard@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2022,
                    Phone = "(888)867-5314",
                    BYUID = 570598087,
                    Position = "TA IS 110",
                    ClassCode = 26562,
                    EmpRecord = 1,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-01-08",
                    PayRate = 16.00,
                    LastPayIncrease = "2022-06-30",
                    PayIncreaseAmount = 0.50,
                    IncreaseInputDate = "2022-06-30",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-01-08",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-01-09",
                    BYUName = "Bernard, Andy",
                },

                new ApplicationResponse
                {
                    FirstName = "Robert",
                    LastName = "California",
                    International = "No",
                    Gender = "Male",
                    Email = "Robert.California@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Spring",
                    Year = 2022,
                    Phone = "(888)867-5315",
                    BYUID = 140541076,
                    Position = "TA IS 110",
                    ClassCode = 26562,
                    EmpRecord = 2,
                    Supervisor = "Jo Bennett",
                    HireDate = "2020-01-09",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-06-30",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-06-30",
                    YearInProgram = "MSB Core (IS or other)",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-01-09",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-01-10",
                    BYUName = "California, Robert",
                },

                new ApplicationResponse
                {
                    FirstName = "Kelly",
                    LastName = "Kapoor",
                    International = "Yes",
                    Gender = "Female",
                    Email = "Kelly.Kapor@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Summer",
                    Year = 2022,
                    Phone = "(888)867-5316",
                    BYUID = 795768466,
                    Position = "TA IS 110",
                    ClassCode = 26562,
                    EmpRecord = 3,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-01-04",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-06-30",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-06-30",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-01-04",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-01-05",
                    BYUName = "Kapoor, Kelly",
                },

                new ApplicationResponse
                {
                    FirstName = "Stanley",
                    LastName = "Hudson",
                    International = "No",
                    Gender = "Male",
                    Email = "Stanley.Hudson@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2020,
                    Phone = "(888)867-5317",
                    BYUID = 199958673,
                    Position = "TA IS 110",
                    ClassCode = 26562,
                    EmpRecord = 0,
                    Supervisor = "Michael Scott",
                    HireDate = "2020-01-04",
                    PayRate = 16.50,
                    LastPayIncrease = "2021-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-08-15",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-01-04",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-01-05",
                    BYUName = "Hudson, Stanley",
                },

                new ApplicationResponse
                {
                    FirstName = "Kevin",
                    LastName = "Malone",
                    International = "No",
                    Gender = "Male",
                    Email = "Kevin.Malone@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2021,
                    Phone = "(888)867-5318",
                    BYUID = 885654609,
                    Position = "TA IS 110",
                    ClassCode = 26562,
                    EmpRecord = 1,
                    Supervisor = "Michael Scott",
                    HireDate = "2021-01-03",
                    PayRate = 16.00,
                    LastPayIncrease = "2021-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-08-15",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2021-01-03",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2021-01-04",
                    BYUName = "Malone, Kevin",
                },

                new ApplicationResponse
                {
                    FirstName = "Meredith",
                    LastName = "Palmer",
                    International = "No",
                    Gender = "Female",
                    Email = "Meredith.Palmer@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Spring",
                    Year = 2022,
                    Phone = "(888)867-5319",
                    BYUID = 286649426,
                    Position = "TA IS 303",
                    ClassCode = 28944,
                    EmpRecord = 2,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-01-03",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-06-30",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-06-30",
                    YearInProgram = "Macc",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-01-03",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-01-04",
                    BYUName = "Palmer, Meredith",
                },

                new ApplicationResponse
                {
                    FirstName = "Angela",
                    LastName = "Martin",
                    International = "Yes",
                    Gender = "Female",
                    Email = "Angela.Martin@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Summer",
                    Year = 2019,
                    Phone = "(888)867-5320",
                    BYUID = 851765258,
                    Position = "RA",
                    ClassCode = 27432,
                    EmpRecord = 3,
                    Supervisor = "Michael Scott",
                    HireDate = "2019-05-14",
                    PayRate = 16.50,
                    LastPayIncrease = "2022-06-30",
                    PayIncreaseAmount = 0.50,
                    IncreaseInputDate = "2022-06-30",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Checked",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2019-05-14",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2019-05-15",
                    BYUName = "Martin, Angela",
                },

                new ApplicationResponse
                {
                    FirstName = "Oscar",
                    LastName = "Martinez",
                    International = "No",
                    Gender = "Male",
                    Email = "Oscar.Martinez@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2020,
                    Phone = "(888)867-5321",
                    BYUID = 238034939,
                    Position = "Office",
                    ClassCode = 23482,
                    EmpRecord = 0,
                    Supervisor = "Michael Scott",
                    HireDate = "2020-05-15",
                    PayRate = 15.50,
                    LastPayIncrease = "2021-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-08-15",
                    YearInProgram = "MSB Core (IS or other)",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Not Yet",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-05-15",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-05-16",
                    BYUName = "Martinez, Oscar",
                },

                new ApplicationResponse
                {
                    FirstName = "Phyllis",
                    LastName = "Vance",
                    International = "No",
                    Gender = "Female",
                    Email = "Phyllis.Vance@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2022,
                    Phone = "(888)867-5322",
                    BYUID = 695098611,
                    Position = "Student Instructor",
                    ClassCode = 28332,
                    EmpRecord = 1,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-05-16",
                    PayRate = 15.50,
                    LastPayIncrease = "",
                    PayIncreaseAmount = 0.00,
                    IncreaseInputDate = "",
                    YearInProgram = "MSB Core (IS or other)",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-05-16",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-05-17",
                    BYUName = "Vance, Phyllis",
                },

                new ApplicationResponse
                {
                    FirstName = "Toby",
                    LastName = "Flenderson",
                    International = "No",
                    Gender = "Male",
                    Email = "Toby.Flenderson@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Spring",
                    Year = 2022,
                    Phone = "(888)867-5323",
                    BYUID = 344053513,
                    Position = "TA IS 201",
                    ClassCode = 26077,
                    EmpRecord = 2,
                    Supervisor = "David Wallace",
                    HireDate = "2022-08-17",
                    PayRate = 15.50,
                    LastPayIncrease = "",
                    PayIncreaseAmount = 0.00,
                    IncreaseInputDate = "",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-08-17",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-08-18",
                    BYUName = "Flenderson, Toby",
                },

                new ApplicationResponse
                {
                    FirstName = "Creed",
                    LastName = "Bratton",
                    International = "Yes",
                    Gender = "Male",
                    Email = "Creed.Bratton@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Summer",
                    Year = 2022,
                    Phone = "(888)867-5324",
                    BYUID = 728979778,
                    Position = "TA IS 303",
                    ClassCode = 28944,
                    EmpRecord = 3,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-08-18",
                    PayRate = 16.00,
                    LastPayIncrease = "",
                    PayIncreaseAmount = 0.00,
                    IncreaseInputDate = "",
                    YearInProgram = "MBA",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-08-18",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-08-19",
                    BYUName = "Bratton, Creed",
                },

                new ApplicationResponse
                {
                    FirstName = "Darryl",
                    LastName = "Philbin",
                    International = "No",
                    Gender = "Male",
                    Email = "Darryl.Philbin@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2020,
                    Phone = "(888)867-5325",
                    BYUID = 770941096,
                    Position = "RA",
                    ClassCode = 27432,
                    EmpRecord = 0,
                    Supervisor = "Michael Scott",
                    HireDate = "2020-01-19",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2021-08-15",
                    YearInProgram = "MPA",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-01-19",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-01-20",
                    BYUName = "Philbin, Darryl",
                },

                new ApplicationResponse
                {
                    FirstName = "Roy",
                    LastName = "Anderson",
                    International = "No",
                    Gender = "Male",
                    Email = "Roy.Anderson@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2021,
                    Phone = "(888)867-5326",
                    BYUID = 889201404,
                    Position = "Office",
                    ClassCode = 23482,
                    EmpRecord = 1,
                    Supervisor = "Michael Scott",
                    HireDate = "2021-01-20",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.50,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "Macc",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2021-01-20",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2021-01-21",
                    BYUName = "Anderson, Roy",
                },

                new ApplicationResponse
                {
                    FirstName = "Erin",
                    LastName = "Hannon",
                    International = "No",
                    Gender = "Female",
                    Email = "Erin.Hannon@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Spring",
                    Year = 2022,
                    Phone = "(888)867-5327",
                    BYUID = 519230023,
                    Position = "Student Instructor",
                    ClassCode = 28332,
                    EmpRecord = 2,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-01-21",
                    PayRate = 16.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "Other majors on campus",
                    PayGradTutition = "No",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-01-21",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-01-22",
                    BYUName = "Hannon, Erin",
                },

                new ApplicationResponse
                {
                    FirstName = "Gabe",
                    LastName = "Lewis",
                    International = "Yes",
                    Gender = "Male",
                    Email = "Gabe.Lewis@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Summer",
                    Year = 2019,
                    Phone = "(888)867-5328",
                    BYUID = 268510065,
                    Position = "Other",
                    ClassCode = 21538,
                    EmpRecord = 3,
                    Supervisor = "Jo Bennett",
                    HireDate = "2019-07-22",
                    PayRate = 16.00,
                    LastPayIncrease = "2022-06-27",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-06-27",
                    YearInProgram = "MSB Core (IS or other)",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Checked",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2019-07-22",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2019-07-23",
                    BYUName = "Lewis, Gabe",
                },

                new ApplicationResponse
                {
                    FirstName = "Clark",
                    LastName = "Green",
                    International = "No",
                    Gender = "Male",
                    Email = "Clark.Green@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2020,
                    Phone = "(888)867-5329",
                    BYUID = 295485746,
                    Position = "TA IS 303",
                    ClassCode = 28944,
                    EmpRecord = 0,
                    Supervisor = "Andy Bernard",
                    HireDate = "2020-05-23",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-06-27",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-06-27",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Not Yet",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-05-23",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-05-24",
                    BYUName = "Green, Clark",
                },

                new ApplicationResponse
                {
                    FirstName = "Pete",
                    LastName = "Miller",
                    International = "No",
                    Gender = "Male",
                    Email = "Pete.Miller@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2022,
                    Phone = "(888)867-5330",
                    BYUID = 647068480,
                    Position = "RA",
                    ClassCode = 27432,
                    EmpRecord = 1,
                    Supervisor = "Andy Bernard",
                    HireDate = "2022-01-24",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-01-24",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-01-25",
                    BYUName = "Miller, Pete",
                },

                new ApplicationResponse
                {
                    FirstName = "David",
                    LastName = "Wallace",
                    International = "No",
                    Gender = "Male",
                    Email = "David.Wallace@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Spring",
                    Year = 2022,
                    Phone = "(888)867-5321",
                    BYUID = 698470632,
                    Position = "Office",
                    ClassCode = 23482,
                    EmpRecord = 2,
                    Supervisor = "John Doe",
                    HireDate = "2022-01-25",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-01-25",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-01-26",
                    BYUName = "Wallace, David",
                },

                new ApplicationResponse
                {
                    FirstName = "Deangelo",
                    LastName = "Vickers",
                    International = "Yes",
                    Gender = "Male",
                    Email = "Deangelo.Vickers@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Summer",
                    Year = 2022,
                    Phone = "(888)867-5332",
                    BYUID = 799372609,
                    Position = "Student Instructor",
                    ClassCode = 28332,
                    EmpRecord = 3,
                    Supervisor = "Jo Bennett",
                    HireDate = "2022-05-26",
                    PayRate = 15.50,
                    LastPayIncrease = "",
                    PayIncreaseAmount = 0.00,
                    IncreaseInputDate = "",
                    YearInProgram = "Macc",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-05-26",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-05-27",
                    BYUName = "Vickers, Deangelo",
                },

                new ApplicationResponse
                {
                    FirstName = "Jo",
                    LastName = "Bennett",
                    International = "No",
                    Gender = "Female",
                    Email = "Jo.Bennett@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2020,
                    Phone = "(888)867-5333",
                    BYUID = 659262545,
                    Position = "Other",
                    ClassCode = 21538,
                    EmpRecord = 0,
                    Supervisor = "John Doe",
                    HireDate = "2020-01-27",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "Other majors on campus",
                    PayGradTutition = "No",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-01-27",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-01-28",
                    BYUName = "Bennett, Jo",
                },

                new ApplicationResponse
                {
                    FirstName = "Josh",
                    LastName = "Porter",
                    International = "No",
                    Gender = "Male",
                    Email = "Josh.Porter@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2021,
                    Phone = "(888)867-5334",
                    BYUID = 780763823,
                    Position = "TA IS 303",
                    ClassCode = 28944,
                    EmpRecord = 1,
                    Supervisor = "Michael Scott",
                    HireDate = "2021-01-28",
                    PayRate = 16.00,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "MSB Core (IS or other)",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2021-01-28",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2021-01-29",
                    BYUName = "Porter, Josh",
                },

                new ApplicationResponse
                {
                    FirstName = "Charles",
                    LastName = "Miner",
                    International = "No",
                    Gender = "Male",
                    Email = "Charles.Miner@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Spring",
                    Year = 2022,
                    Phone = "(888)867-5335",
                    BYUID = 554508642,
                    Position = "TA IS 201",
                    ClassCode = 26077,
                    EmpRecord = 2,
                    Supervisor = "David Wallace",
                    HireDate = "2022-01-29",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-06-27",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-06-27",
                    YearInProgram = "MSB Core (IS or other)",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-01-29",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-01-30",
                    BYUName = "Miner, Charles",
                },

                new ApplicationResponse
                {
                    FirstName = "Ed",
                    LastName = "Truck",
                    International = "Yes",
                    Gender = "Male",
                    Email = "Ed.Truck@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Summer",
                    Year = 2019,
                    Phone = "(888)867-5336",
                    BYUID = 671138173,
                    Position = "Office",
                    ClassCode = 23482,
                    EmpRecord = 3,
                    Supervisor = "Jan Levinson",
                    HireDate = "2019-01-30",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "Yes",
                    TerminationDate = "2022-09-31",
                    QualtricsSurveySent = "Checked",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2019-01-30",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2019-01-31",
                    BYUName = "Truck, Ed",
                },

                new ApplicationResponse
                {
                    FirstName = "Dan",
                    LastName = "Gore",
                    International = "No",
                    Gender = "Male",
                    Email = "Dan.Gore@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2020,
                    Phone = "(888)867-5337",
                    BYUID = 466543887,
                    Position = "Student Instructor",
                    ClassCode = 28332,
                    EmpRecord = 0,
                    Supervisor = "Michael Scott",
                    HireDate = "2020-06-30",
                    PayRate = 16.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Not Yet",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2020-06-30",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2020-06-30",
                    BYUName = "Gore, Dan",
                },

                new ApplicationResponse
                {
                    FirstName = "Troy",
                    LastName = "Underbridge",
                    International = "No",
                    Gender = "Male",
                    Email = "Troy.Underbridge@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2022,
                    Phone = "(888)867-5338",
                    BYUID = 541142770,
                    Position = "Other",
                    ClassCode = 21538,
                    EmpRecord = 1,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-06-01",
                    PayRate = 16.00,
                    LastPayIncrease = "",
                    PayIncreaseAmount = 0.00,
                    IncreaseInputDate = "",
                    YearInProgram = "MiSM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-06-01",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-06-02",
                    BYUName = "Underbridge, Troy",
                },

                new ApplicationResponse
                {
                    FirstName = "Karen",
                    LastName = "Filippelli",
                    International = "No",
                    Gender = "Female",
                    Email = "Karen.Filippelli@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Spring",
                    Year = 2022,
                    Phone = "(888)867-5339",
                    BYUID = 463568593,
                    Position = "TA IS 303",
                    ClassCode = 28944,
                    EmpRecord = 2,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-06-02",
                    PayRate = 15.50,
                    LastPayIncrease = "",
                    PayIncreaseAmount = 0.00,
                    IncreaseInputDate = "",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-06-02",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-06-03",
                    BYUName = "Filippelli, Karen",
                },

                new ApplicationResponse
                {
                    FirstName = "Danny",
                    LastName = "Cordray",
                    International = "Yes",
                    Gender = "Male",
                    Email = "Danny.Cordray@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Summer",
                    Year = 2022,
                    Phone = "(888)867-5340",
                    BYUID = 116926991,
                    Position = "RA",
                    ClassCode = 27432,
                    EmpRecord = 3,
                    Supervisor = "Michael Scott",
                    HireDate = "2022-08-03",
                    PayRate = 15.50,
                    LastPayIncrease = "",
                    PayIncreaseAmount = 0.00,
                    IncreaseInputDate = "",
                    YearInProgram = "Other majors on campus",
                    PayGradTutition = "No",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-08-03",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-08-04",
                    BYUName = "Cordray, Danny",
                },

                new ApplicationResponse
                {
                    FirstName = "Ben",
                    LastName = "Nugent",
                    International = "No",
                    Gender = "Male",
                    Email = "Ben.Nugent@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Fall",
                    Year = 2021,
                    Phone = "(888)867-5341",
                    BYUID = 448416842,
                    Position = "Office",
                    ClassCode = 23482,
                    EmpRecord = 0,
                    Supervisor = "Michael Scott",
                    HireDate = "2021-02-04",
                    PayRate = 15.50,
                    LastPayIncrease = "2022-08-15",
                    PayIncreaseAmount = 0.25,
                    IncreaseInputDate = "2022-08-15",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2021-02-04",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2021-02-05",
                    BYUName = "Nugent, Ben",
                },

                new ApplicationResponse
                {
                    FirstName = "Todd",
                    LastName = "Packer",
                    International = "No",
                    Gender = "Male",
                    Email = "Todd.Packer@dundermifflin.fake",
                    Hours = "20 hrs/wk",
                    Semester = "Winter",
                    Year = 2022,
                    Phone = "(888)867-5342",
                    BYUID = 936684305,
                    Position = "TA IS 201",
                    ClassCode = 26077,
                    EmpRecord = 1,
                    Supervisor = "David Wallace",
                    HireDate = "2022-02-05",
                    PayRate = 15.50,
                    LastPayIncrease = "",
                    PayIncreaseAmount = 0.00,
                    IncreaseInputDate = "",
                    YearInProgram = "MISM",
                    PayGradTutition = "Yes",
                    NameChangeCompleted = "Yes",
                    Notes = "",
                    Terminated = "",
                    TerminationDate = "",
                    QualtricsSurveySent = "Sent",
                    SubmittedEform = "Yes",
                    FormSubmissionDate = "2022-02-05",
                    AuthorizationToWork = "Yes",
                    AuthorizationEmailDate = "2022-02-06",
                    BYUName = "Packer, Todd",
                }
            );
        }
    }
}
